<a href="https://colab.research.google.com/github/kwon0136/MachineLearning/blob/master/190410/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://kkokkilkon.tistory.com/19

In [0]:
xdata = [
    [1,2],
    [2,1],
    [2,3],
    [4,1],
    [5,1],
    [4,2],
    [6,4]
]
ydata = [
    [0],
    [0],
    [0],
    [1],
    [1],
    [0],
    [1]
]

In [0]:
import tensorflow as tf

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [0]:
W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

https://pythonkim.tistory.com/22

In [0]:
# Hypothesis sigmoid

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = tf.reduce_mean(Y + tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

###cast()
텐서를 새로운 형태로 캐스팅하는데 사용한다.

부동소수점형에서 정수형으로 바꾼 경우 소수점 버린을 한다.

Boolean형태인 경우 True이면 1, False이면 0을 출력한다.

In [0]:
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
#h>=0.5 : 1, h<0.5: 0

accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for s in range(2000):
  cost_val, _ = sess.run([cost, train], feed_dict={X:xdata, Y:ydata})
  if s % 200 == 0:
    print(s, cost_val)
  h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:xdata, Y:ydata})
  print(h, c, a)

0 -0.7324891
[[0.60192287]
 [0.66244215]
 [0.86045486]
 [0.912176  ]
 [0.9598305 ]
 [0.9484822 ]
 [0.9967444 ]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.42857143
[[0.607531  ]
 [0.6679103 ]
 [0.8649025 ]
 [0.915307  ]
 [0.9616157 ]
 [0.95069474]
 [0.9969771 ]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.42857143
[[0.61320627]
 [0.6734273 ]
 [0.86930275]
 [0.9183879 ]
 [0.9633534 ]
 [0.95285267]
 [0.9971968 ]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.42857143
[[0.6189453 ]
 [0.6789889 ]
 [0.8736507 ]
 [0.9214158 ]
 [0.96504277]
 [0.9549545 ]
 [0.9974038 ]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.42857143
[[0.62474465]
 [0.68459094]
 [0.87794214]
 [0.9243879 ]
 [0.96668273]
 [0.95699906]
 [0.9975986 ]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.42857143
[[0.63060045]
 [0.6902289 ]
 [0.88217264]
 [0.9273015 ]
 [0.96827286]
 [0.95898545]
 [0.99778146]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 0.42857143
[[0.63650864]
 [0.6958981 ]
 [0.88633823]
 [0.9301546 ]
 [0.9698127 ]